### ISSUE TITLE
GPI crashes with multiplayer after latest changes

### ISSUE THREAD

**Issue by tyler27** [runetopic/osrs-server#13]
```
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] 2023-03-22 16:57:04 [Client] ERROR injected-client - Game crash: 3,89,89,3,3229,3233,16,127,-16,
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] java.lang.RuntimeException: null
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] 	at ch.v(class85.java:154)
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] 	at kw.w(class310.java:73)
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] 	at client.ij(Client.java:6988)
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] 	at client.fp(Client.java:3261)
2023-03-22T16:57:04.858-0400 [QUIET] [system.out] 	at client.ax(Client.java:1349)
2023-03-22T16:57:04.859-0400 [QUIET] [system.out] 	at aj.d(GameEngine.java:377)
2023-03-22T16:57:04.859-0400 [QUIET] [system.out] 	at aj.run(GameEngine.java:356)
2023-03-22T16:57:04.859-0400 [QUIET] [system.out] 	at java.base/java.lang.Thread.run(Thread.java:831)```

**Comment by ultraviolet-jordan** [comment]
![image](https://user-images.githubusercontent.com/76214316/227044731-d2383d9b-975d-466e-84d7-947c75c43fcf.png)

**Comment by tyler27** [comment]
Alright, looks like your changes need to be reverted then.

**Comment by ultraviolet-jordan** [comment]
The problem: Inside PlayerInfoPacketBuilder the way the bits were being tracked when writing to the buffer was slightly wrong. This is for both of the recursion functions 'syncHighDefinition' and 'syncLowDefinition'. The bits were being misaligned after the recent commit of creating the RSByteBuffer class.

The solution: Created the 'rewindBits' function inside RSByteBuffer to allow the proper tracking/positioning of the buffer when building the PlayerInfoPacketBuilder.
